# Development overrides for docker-compose.yml
# This file is automatically loaded by docker-compose and provides development-specific settings

version: '3.8'

services:
  backend:
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    environment:
      - DEBUG=true
      - RELOAD=true
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

  mongodb:
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123